// AUTO-GENERATED by scripts/build-catalog.ts — DO NOT EDIT.
// Source of truth: sources/<id>/source.json. Regenerate with: npm run catalog

import type { SourceSpec } from "./schema.js";

export const SOURCES: readonly SourceSpec[] = [
  {
    "id": "bea",
    "name": "BEA — Bureau of Economic Analysis API",
    "agency": "U.S. Bureau of Economic Analysis",
    "category": "economy",
    "status": "live",
    "api": {
      "baseUrl": "https://apps.bea.gov/api",
      "protocol": "rest-json",
      "docsUrl": "https://apps.bea.gov/api/_pdf/bea_web_service_api_user_guide.pdf",
      "endpoints": [
        {
          "id": "data",
          "path": "/data",
          "method": "GET",
          "description": "Single endpoint; the method= param selects the operation (GetData, GetDataSetList, GetParameterList, GetParameterValues)."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "UserID",
      "credentialRef": "env:BEA_API_KEY",
      "signupUrl": "https://apps.bea.gov/API/signup/"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "Free UserID key required. Throttle: max 100 requests, 100MB, and 30 errors per minute per IP/key — exceeding it blocks for 1 hour."
    },
    "llmDocs": {
      "summary": "US economic accounts: GDP (NIPA), regional income/GDP, input-output, international trade and investment, and fixed assets.",
      "queryGuide": "One endpoint, /data; the operation is chosen by method=. Discover structure first: method=GetDataSetList, then GetParameterList&datasetname=, then GetParameterValues&datasetname=&ParameterName=. Then method=GetData&datasetname=<ds>&<params>&ResultFormat=JSON. UserID is injected by the gateway.",
      "exampleQueries": [
        {
          "intent": "List available datasets",
          "request": {
            "method": "GET",
            "path": "/data",
            "params": {
              "method": "GetDataSetList",
              "ResultFormat": "JSON"
            }
          }
        },
        {
          "intent": "Annual real GDP (NIPA table T10101)",
          "request": {
            "method": "GET",
            "path": "/data",
            "params": {
              "method": "GetData",
              "datasetname": "NIPA",
              "TableName": "T10101",
              "Frequency": "A",
              "Year": "2023",
              "ResultFormat": "JSON"
            }
          }
        }
      ],
      "gotchas": [
        "Everything goes through one /data endpoint — the method= param picks the operation, not the URL path.",
        "Add ResultFormat=JSON — the default is XML.",
        "Walk the metadata methods (GetParameterList/GetParameterValues) to learn each dataset's required params before GetData.",
        "Requires a free key (BEA_API_KEY, sent as UserID); without it the gateway returns 503."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://apps.bea.gov/api/_pdf/bea_web_service_api_user_guide.pdf",
      "redistributionNotes": "US federal data, public domain. Terms require attribution and prohibit implying BEA endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/bea.ts"
    }
  },
  {
    "id": "bls-public-data",
    "name": "BLS Public Data API",
    "agency": "Bureau of Labor Statistics",
    "category": "economy",
    "status": "live",
    "api": {
      "baseUrl": "https://api.bls.gov/publicAPI/v2",
      "protocol": "rest-json",
      "docsUrl": "https://www.bls.gov/developers/",
      "endpoints": [
        {
          "id": "timeseries",
          "path": "/timeseries/data/",
          "method": "POST",
          "description": "Fetch one or more series by ID over a year range"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "body",
      "paramName": "registrationkey",
      "credentialRef": "env:BLS_API_KEY",
      "signupUrl": "https://data.bls.gov/registrationEngine/"
    },
    "limits": {
      "dailyQuota": 500,
      "perRequestMaxSeries": 50,
      "rateLimitBehavior": "hard-reject",
      "notes": "Quota is per key — multiplexing risk, monitor usage"
    },
    "llmDocs": {
      "summary": "US labor statistics: unemployment, CPI, wages, employment by industry and region.",
      "queryGuide": "Series IDs are structured codes, e.g. LAUCN040010000000005 = Local Area Unemployment, county-level. Prefix determines survey: LA=local unemployment, CU=CPI urban, CE=employment. BLS is the authoritative/primary source for US CPI and inflation. CPI-U all-items (US city average, not seasonally adjusted) is series CUUR0000SA0. To compute an inflation rate from CPI: pull CUUR0000SA0 over a year range, take the index value for a month and the SAME month 12 months earlier, and compute year-over-year percent change = (newer - older) / older * 100. Each data point in Results.series[].data[] has year, period (M01-M12), and value (the index level).",
      "exampleQueries": [
        {
          "intent": "National unemployment rate, 2024-2026",
          "request": {
            "method": "POST",
            "path": "/timeseries/data/",
            "body": {
              "seriesid": [
                "LNS14000000"
              ],
              "startyear": "2024",
              "endyear": "2026"
            }
          }
        },
        {
          "intent": "CPI (all urban consumers, all items), 2024-2026",
          "request": {
            "method": "POST",
            "path": "/timeseries/data/",
            "body": {
              "seriesid": [
                "CUUR0000SA0"
              ],
              "startyear": "2024",
              "endyear": "2026"
            }
          }
        },
        {
          "intent": "Year-over-year CPI inflation rate (CPI-U all items): pull two June points 12 months apart, then % change",
          "request": {
            "method": "POST",
            "path": "/timeseries/data/",
            "body": {
              "seriesid": [
                "CUUR0000SA0"
              ],
              "startyear": "2022",
              "endyear": "2023"
            }
          }
        }
      ],
      "gotchas": [
        "POST not GET for multi-series",
        "Years are strings, not ints",
        "No discovery endpoint — series IDs must be constructed or known",
        "For CPI/inflation, CUUR0000SA0 is the canonical CPI-U all-items series; compute inflation as YoY % change between same-month points 12 months apart."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.bls.gov/developers/termsOfService.htm",
      "redistributionNotes": "ToS prohibits sharing registration keys; centralized key use needs review",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/bls.ts"
    }
  },
  {
    "id": "census-acs",
    "name": "US Census Bureau — American Community Survey",
    "agency": "U.S. Census Bureau",
    "category": "demographics",
    "status": "live",
    "api": {
      "baseUrl": "https://api.census.gov/data",
      "protocol": "rest-json",
      "docsUrl": "https://www.census.gov/data/developers/data-sets/acs-5year.html",
      "endpoints": [
        {
          "id": "acs5",
          "path": "/{year}/acs/acs5",
          "method": "GET",
          "description": "ACS 5-year detailed tables: select variables with get=, geography with for=/in="
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "key",
      "credentialRef": "env:CENSUS_API_KEY",
      "signupUrl": "https://api.census.gov/data/key_signup.html"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "Calls without a key are limited to ~500/day per IP; a free key raises the cap. Max 50 variables per get= request."
    },
    "llmDocs": {
      "summary": "US population, income, housing, education and demographic estimates by geography (nation, state, county, tract, block group).",
      "queryGuide": "Returns a JSON array-of-arrays; row 0 is the header. Select variables via get= (e.g. NAME,B01001_001E) and geography via for=/in=. e.g. B01001_001E = total population.",
      "exampleQueries": [
        {
          "intent": "Total population by state, 2022 ACS5",
          "request": {
            "method": "GET",
            "path": "/2022/acs/acs5",
            "params": {
              "get": "NAME,B01001_001E",
              "for": "state:*"
            }
          }
        },
        {
          "intent": "Median household income for one county",
          "request": {
            "method": "GET",
            "path": "/2022/acs/acs5",
            "params": {
              "get": "NAME,B19013_001E",
              "for": "county:031",
              "in": "state:08"
            }
          }
        }
      ],
      "gotchas": [
        "Response is array-of-arrays, not array-of-objects",
        "Variable codes end in E for estimate, M for margin of error",
        "Geography hierarchy matters: 'in=' is required for sub-state geos"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.census.gov/data/developers/about/terms-of-service.html",
      "redistributionNotes": "US federal data, public domain. ToS requires attribution and prohibits implying Census endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/census-acs.ts"
    }
  },
  {
    "id": "clinical-trials",
    "name": "ClinicalTrials.gov — study registry (v2)",
    "agency": "U.S. National Library of Medicine (NIH)",
    "category": "health",
    "status": "live",
    "api": {
      "baseUrl": "https://clinicaltrials.gov/api/v2",
      "protocol": "rest-json",
      "docsUrl": "https://clinicaltrials.gov/data-api/api",
      "endpoints": [
        {
          "id": "studies-search",
          "path": "/studies",
          "method": "GET",
          "description": "Search registered studies by term, condition, status, location; supports field selection and paging."
        },
        {
          "id": "study-by-id",
          "path": "/studies/{nctId}",
          "method": "GET",
          "description": "Full record for one study by NCT id (e.g. NCT01884792)."
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key. Roughly 50 requests/minute per IP. Default pageSize is 10; set it explicitly. Max pageSize 1000."
    },
    "llmDocs": {
      "summary": "Registry of clinical studies worldwide: conditions, interventions, eligibility, sponsors, status, locations, and results.",
      "queryGuide": "GET /studies with query.* and filter.* params. Free text via query.term; structured search via query.cond (condition), query.intr (intervention), query.locn (location). Filter enums with filter.overallStatus (RECRUITING, COMPLETED, ...). Reduce payload with fields=NCTId,BriefTitle,OverallStatus. Page with pageSize and the nextPageToken returned in each response (pass it as pageToken). Fetch one record with /studies/{nctId}.",
      "exampleQueries": [
        {
          "intent": "Recruiting diabetes studies, key fields only",
          "request": {
            "method": "GET",
            "path": "/studies",
            "params": {
              "query.cond": "diabetes",
              "filter.overallStatus": "RECRUITING",
              "fields": "NCTId,BriefTitle,OverallStatus",
              "pageSize": "5"
            }
          }
        },
        {
          "intent": "Full record for one trial by NCT id",
          "request": {
            "method": "GET",
            "path": "/studies/NCT01884792"
          }
        }
      ],
      "gotchas": [
        "Records are deeply nested under protocolSection.<module> (identificationModule, statusModule, ...) — fields= takes leaf names like NCTId, not dotted paths.",
        "Default pageSize is 10 — set it explicitly or you silently get a short page.",
        "Pagination is token-based: read nextPageToken from the response and resend it as pageToken (no offset/skip).",
        "Status filters are uppercase enums: RECRUITING, COMPLETED, TERMINATED, NOT_YET_RECRUITING."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://clinicaltrials.gov/about-site/terms-conditions",
      "redistributionNotes": "US federal (NIH/NLM) data, public domain. Terms request attribution and that data not be presented as if endorsed by NLM.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/clinical-trials.ts"
    }
  },
  {
    "id": "congress-gov",
    "name": "Congress.gov API",
    "agency": "Library of Congress",
    "category": "legislative",
    "status": "live",
    "api": {
      "baseUrl": "https://api.congress.gov/v3",
      "protocol": "rest-json",
      "docsUrl": "https://gpo.congress.gov/",
      "endpoints": [
        {
          "id": "bill",
          "path": "/bill/{congress}/{billType}/{billNumber}",
          "method": "GET",
          "description": "Bill detail by congress, type (hr, s, hjres, ...), and number; list endpoints at /bill and /bill/{congress}."
        },
        {
          "id": "member",
          "path": "/member/{bioguideId}",
          "method": "GET",
          "description": "Member profile by bioguide id; list at /member."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:CONGRESS_API_KEY",
      "signupUrl": "https://api.congress.gov/sign-up/"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "Free api.data.gov key required. ~5000 requests/hour per key, then HTTP 429. Default limit 20, max 250 per page."
    },
    "llmDocs": {
      "summary": "US legislative data: bills, amendments, members, committees, the Congressional Record, nominations, and treaties from 1973 onward.",
      "queryGuide": "Append ?format=json and the api_key (injected by the gateway). Resource lists at /bill, /member, /committee, /nomination; detail at /bill/{congress}/{billType}/{billNumber}. Page with offset and limit (max 250). Filter bill lists by fromDateTime/toDateTime and sort.",
      "exampleQueries": [
        {
          "intent": "Detail for H.R. 1 of the 118th Congress",
          "request": {
            "method": "GET",
            "path": "/bill/118/hr/1",
            "params": {
              "format": "json"
            }
          }
        },
        {
          "intent": "Most recently updated bills",
          "request": {
            "method": "GET",
            "path": "/bill",
            "params": {
              "format": "json",
              "sort": "updateDate+desc",
              "limit": "20"
            }
          }
        }
      ],
      "gotchas": [
        "Add format=json — the default response is XML.",
        "billType is lowercase (hr, s, hjres, sjres, hconres, sconres, hres, sres).",
        "Paging is offset/limit, limit max 250.",
        "Requires a free api.data.gov key (CONGRESS_API_KEY); without it the gateway returns 503."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.congress.gov/about/data-and-api",
      "redistributionNotes": "US legislative data, public domain. api.data.gov key-sharing ToS applies — review before going live.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/congress-gov.ts"
    }
  },
  {
    "id": "eia",
    "name": "EIA Energy Data API (v2)",
    "agency": "U.S. Energy Information Administration",
    "category": "energy",
    "status": "live",
    "api": {
      "baseUrl": "https://api.eia.gov/v2",
      "protocol": "rest-json",
      "docsUrl": "https://www.eia.gov/opendata/documentation.php",
      "endpoints": [
        {
          "id": "route-data",
          "path": "/{route}/data",
          "method": "GET",
          "description": "Time-series data for a route (e.g. /electricity/retail-sales/data); pick facets, frequency, and data columns."
        },
        {
          "id": "route-metadata",
          "path": "/{route}",
          "method": "GET",
          "description": "Browse the route tree: child routes, available frequencies, facets, and data columns."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:EIA_API_KEY",
      "signupUrl": "https://www.eia.gov/opendata/register.php"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "Free key required (api_key query param). Up to 5000 rows per request; page with offset/length."
    },
    "llmDocs": {
      "summary": "US energy statistics: electricity prices and generation, petroleum, natural gas, coal, renewables, CO2 emissions, and international energy.",
      "queryGuide": "The API is a route tree. GET a route (e.g. /electricity/retail-sales) to discover its frequencies, facets, and data columns, then GET /{route}/data with data[]=<column>, frequency=, facets[<id>][]=<value>, start=, end=, sort[0][column]=&sort[0][direction]=, offset, length (max 5000). api_key is injected by the gateway.",
      "exampleQueries": [
        {
          "intent": "Browse the electricity retail-sales route metadata",
          "request": {
            "method": "GET",
            "path": "/electricity/retail-sales"
          }
        },
        {
          "intent": "Monthly average retail electricity price, all sectors",
          "request": {
            "method": "GET",
            "path": "/electricity/retail-sales/data",
            "params": {
              "frequency": "monthly",
              "data[]": "price",
              "start": "2023-01",
              "length": "12"
            }
          }
        }
      ],
      "gotchas": [
        "Two-step: read a route's metadata to learn valid data[] columns and facet ids before requesting /data.",
        "data columns and facets use bracketed array params: data[]=price, facets[stateid][]=CA.",
        "length maxes at 5000 rows — page with offset.",
        "Requires a free key (EIA_API_KEY); without it the gateway returns 503."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.eia.gov/about/copyrights_reuse.php",
      "redistributionNotes": "US federal data, public domain. Free to redistribute; attribution to EIA requested.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/eia.ts"
    }
  },
  {
    "id": "epa-airnow",
    "name": "EPA AirNow API",
    "agency": "Environmental Protection Agency",
    "category": "environment",
    "status": "live",
    "api": {
      "baseUrl": "https://www.airnowapi.org",
      "protocol": "rest-json",
      "docsUrl": "https://docs.airnowapi.org/",
      "endpoints": [
        {
          "id": "observation-by-zip",
          "path": "/aq/observation/zipCode/current/",
          "method": "GET",
          "description": "Current AQI observations by ZIP code"
        },
        {
          "id": "observation-by-latlon",
          "path": "/aq/observation/latLong/current/",
          "method": "GET",
          "description": "Current AQI observations by lat/lon"
        },
        {
          "id": "forecast-by-zip",
          "path": "/aq/forecast/zipCode/",
          "method": "GET",
          "description": "AQI forecast by ZIP code"
        },
        {
          "id": "data",
          "path": "/aq/data/",
          "method": "GET",
          "description": "Raw monitoring data by bounding box and parameter over a time range"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "API_KEY",
      "credentialRef": "env:AIRNOW_API_KEY",
      "signupUrl": "https://docs.airnowapi.org/account/request/"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "hard-reject",
      "notes": "Default rate limit ~500 requests/hour per key (confirm in account dashboard). Verify exact hourly cap before relying on it."
    },
    "llmDocs": {
      "summary": "Real-time and forecast US air quality (AQI) for ozone, PM2.5, PM10 by ZIP, lat/lon, or bounding box.",
      "queryGuide": "Use zipCode or latLong observation endpoints for point lookups; use /aq/data/ with a bounding box (BBOX) for area scans. Request format=application/json explicitly.",
      "exampleQueries": [
        {
          "intent": "Current AQI for ZIP 90210 (25-mile radius)",
          "request": {
            "method": "GET",
            "path": "/aq/observation/zipCode/current/",
            "params": {
              "format": "application/json",
              "zipCode": "90210",
              "distance": "25"
            }
          }
        },
        {
          "intent": "AQI forecast by lat/lon for a date",
          "request": {
            "method": "GET",
            "path": "/aq/forecast/latLong/",
            "params": {
              "format": "application/json",
              "latitude": "34.09",
              "longitude": "-118.41",
              "date": "2026-06-11"
            }
          }
        }
      ],
      "gotchas": [
        "format parameter is literally 'application/json' as a query value, not an Accept header.",
        "Coverage gaps where no nearby monitor exists; empty array means no station in range, not an error.",
        "Hourly rate limit is enforced and resets hourly; batch/cache aggressively."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://docs.airnowapi.org/faq",
      "redistributionNotes": "US federal data, public domain. AirNow ToS requires attribution to AirNow and prohibits implying EPA endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/epa-airnow.ts"
    }
  },
  {
    "id": "fdic-bankfind",
    "name": "FDIC BankFind Suite",
    "agency": "Federal Deposit Insurance Corporation",
    "category": "finance",
    "status": "live",
    "api": {
      "baseUrl": "https://api.fdic.gov/banks",
      "protocol": "rest-json",
      "docsUrl": "https://api.fdic.gov/banks/docs/",
      "endpoints": [
        {
          "id": "institutions",
          "path": "/institutions",
          "method": "GET",
          "description": "Search FDIC-insured institutions by name, location, charter, and status."
        },
        {
          "id": "financials",
          "path": "/financials",
          "method": "GET",
          "description": "Quarterly financial/call-report metrics per institution (by CERT)."
        },
        {
          "id": "failures",
          "path": "/failures",
          "method": "GET",
          "description": "Historical bank failures and assistance transactions."
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key. Default limit is 10; max limit per request is 10000. Paginate with offset. No published hard quota."
    },
    "llmDocs": {
      "summary": "FDIC-insured bank directory, quarterly financial metrics, and historical failures, searchable by name, location, and identifier.",
      "queryGuide": "GET /institutions, /financials, or /failures. Narrow with filters (Elasticsearch-style field:value, e.g. STALP:CA, joined with AND/OR), full-text with search, choose columns with fields (comma-separated), page with limit and offset, sort with sort_by and sort_order. format=json is the default. Discover field names from the docs (e.g. NAME, CITY, STALP, CERT, ACTIVE).",
      "exampleQueries": [
        {
          "intent": "Active California banks, name and city only",
          "request": {
            "method": "GET",
            "path": "/institutions",
            "params": {
              "filters": "STALP:CA AND ACTIVE:1",
              "fields": "NAME,CITY,STALP,CERT",
              "limit": "5"
            }
          }
        },
        {
          "intent": "Bank failures in Illinois since 2008",
          "request": {
            "method": "GET",
            "path": "/failures",
            "params": {
              "filters": "PSTALP:IL AND FAILYR:[2008 TO 2025]",
              "fields": "NAME,CITYST,FAILDATE",
              "sort_by": "FAILDATE",
              "sort_order": "DESC",
              "limit": "10"
            }
          }
        }
      ],
      "gotchas": [
        "Host migrated: the API is now api.fdic.gov/banks (the old banks.data.fdic.gov/api 301-redirects here).",
        "Records are wrapped: each result is { data: {...}, score }, and the top level has meta.total — read .data[].data.",
        "filters uses Elasticsearch query syntax: field:value, AND/OR, and ranges like FAILYR:[2008 TO 2025].",
        "Default limit is 10 — set limit explicitly and paginate with offset for full pulls."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.fdic.gov/policies/website-policies",
      "redistributionNotes": "US federal data, public domain. Free to redistribute; attribution to FDIC requested.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/fdic-bankfind.ts"
    }
  },
  {
    "id": "federal-register",
    "name": "Federal Register API",
    "agency": "Office of the Federal Register / GPO",
    "category": "regulations",
    "status": "live",
    "api": {
      "baseUrl": "https://www.federalregister.gov/api/v1",
      "protocol": "rest-json",
      "docsUrl": "https://www.federalregister.gov/developers/documentation/api/v1",
      "endpoints": [
        {
          "id": "documents-search",
          "path": "/documents.json",
          "method": "GET",
          "description": "Search Federal Register documents (rules, proposed rules, notices, presidential docs) by term, agency, type, and date."
        },
        {
          "id": "document-by-number",
          "path": "/documents/{document_number}.json",
          "method": "GET",
          "description": "Full metadata for a single document by its Federal Register document number."
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key. per_page max 1000; results capped at 2000 documents per search (page beyond that is rejected). No published hard quota."
    },
    "llmDocs": {
      "summary": "The daily journal of the US federal government: final and proposed rules, agency notices, and presidential documents, searchable by term, agency, type, and date.",
      "queryGuide": "GET /documents.json with conditions[*] filters: conditions[term] (full text), conditions[agencies][] (agency slug, e.g. securities-and-exchange-commission), conditions[type][] (RULE, PRORULE, NOTICE, PRESDOCU), conditions[publication_date][gte]/[lte] (YYYY-MM-DD). Choose returned columns with fields[] (e.g. title, type, publication_date, html_url). Page with per_page and page. Fetch one document by number with /documents/{document_number}.json.",
      "exampleQueries": [
        {
          "intent": "Recent proposed rules mentioning 'privacy'",
          "request": {
            "method": "GET",
            "path": "/documents.json",
            "params": {
              "conditions[term]": "privacy",
              "conditions[type][]": "PRORULE",
              "per_page": "5",
              "order": "newest"
            }
          }
        },
        {
          "intent": "SEC documents published in a date range",
          "request": {
            "method": "GET",
            "path": "/documents.json",
            "params": {
              "conditions[agencies][]": "securities-and-exchange-commission",
              "conditions[publication_date][gte]": "2024-01-01",
              "conditions[publication_date][lte]": "2024-03-31",
              "fields[]": "title",
              "per_page": "10"
            }
          }
        }
      ],
      "gotchas": [
        "Filters are bracketed: conditions[term], conditions[type][], conditions[publication_date][gte] — array filters need the trailing [].",
        "document type codes are RULE, PRORULE (proposed), NOTICE, PRESDOCU.",
        "agencies are referenced by slug, not display name (securities-and-exchange-commission).",
        "Deep pagination is capped (~2000 results); narrow with date/agency conditions rather than paging far."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.federalregister.gov/reader-aids/developer-resources",
      "redistributionNotes": "US federal data, public domain. Free to redistribute; attribution requested.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/federal-register.ts"
    }
  },
  {
    "id": "fema-open",
    "name": "OpenFEMA — disasters, NFIP & assistance",
    "agency": "Federal Emergency Management Agency",
    "category": "emergency-management",
    "status": "live",
    "api": {
      "baseUrl": "https://www.fema.gov/api/open",
      "protocol": "rest-json",
      "docsUrl": "https://www.fema.gov/about/openfema/api",
      "endpoints": [
        {
          "id": "disaster-declarations",
          "path": "/v2/DisasterDeclarationsSummaries",
          "method": "GET",
          "description": "Summary of every FEMA disaster declaration (state, incident type, dates, program)."
        },
        {
          "id": "nfip-claims",
          "path": "/v2/FimaNfipClaims",
          "method": "GET",
          "description": "National Flood Insurance Program redacted claims data."
        },
        {
          "id": "data-sets",
          "path": "/v1/DataSets",
          "method": "GET",
          "description": "Catalog of every OpenFEMA dataset and its current version (use to discover entity names/versions)."
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key. $top caps at 10000 records per request; default page size is 1000. Paginate with $skip. No published hard quota."
    },
    "llmDocs": {
      "summary": "FEMA disaster declarations, National Flood Insurance Program claims, and individual/public assistance, queryable by state, incident type, and date.",
      "queryGuide": "Each dataset is a versioned path, e.g. /v2/DisasterDeclarationsSummaries. Filter with OData params: $filter (e.g. state eq 'TX'), $top (max 10000), $skip, $orderby, $select. Append $inlinecount=allpages&$metadata=off to control the metadata envelope. Call /v1/DataSets to discover entity names and their latest version.",
      "exampleQueries": [
        {
          "intent": "Most recent 5 disaster declarations in Texas",
          "request": {
            "method": "GET",
            "path": "/v2/DisasterDeclarationsSummaries",
            "params": {
              "$filter": "state eq 'TX'",
              "$orderby": "declarationDate desc",
              "$top": "5"
            }
          }
        },
        {
          "intent": "Count of all NFIP flood claims for a county FIPS",
          "request": {
            "method": "GET",
            "path": "/v2/FimaNfipClaims",
            "params": {
              "$filter": "countyCode eq '48201'",
              "$top": "1",
              "$inlinecount": "allpages"
            }
          }
        }
      ],
      "gotchas": [
        "Filter/order params use the OData $ prefix: $filter, $top, $skip, $orderby, $select.",
        "$filter string values use single quotes: state eq 'TX'.",
        "Default page size is 1000 and $top maxes at 10000 — paginate large pulls with $skip.",
        "Datasets are versioned (v1/v2/...); a renamed/retired version 404s. Check /v1/DataSets for the current version path."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.fema.gov/about/openfema/terms-conditions",
      "redistributionNotes": "US federal data, public domain. OpenFEMA terms require attribution and prohibit implying FEMA endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/fema-open.ts"
    }
  },
  {
    "id": "fred",
    "name": "FRED — Federal Reserve Economic Data",
    "agency": "Federal Reserve Bank of St. Louis",
    "category": "economy",
    "status": "live",
    "api": {
      "baseUrl": "https://api.stlouisfed.org/fred",
      "protocol": "rest-json",
      "docsUrl": "https://fred.stlouisfed.org/docs/api/fred/",
      "endpoints": [
        {
          "id": "series-observations",
          "path": "/series/observations",
          "method": "GET",
          "description": "Observation values for an economic data series by series_id"
        },
        {
          "id": "series-search",
          "path": "/series/search",
          "method": "GET",
          "description": "Search series by text"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:FRED_API_KEY",
      "signupUrl": "https://fredaccount.stlouisfed.org/apikeys"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "hard-reject",
      "notes": "120 requests/minute per key. Default response is XML — request file_type=json explicitly."
    },
    "llmDocs": {
      "summary": "US and international macroeconomic time series: GDP, inflation, interest rates, employment, money supply.",
      "queryGuide": "Identify a series_id (e.g. GDP, CPIAUCSL, UNRATE) then call /series/observations?series_id=...&file_type=json. Use /series/search to discover series_ids.",
      "exampleQueries": [
        {
          "intent": "Monthly CPI (all urban consumers) observations",
          "request": {
            "method": "GET",
            "path": "/series/observations",
            "params": {
              "series_id": "CPIAUCSL",
              "file_type": "json"
            }
          }
        },
        {
          "intent": "Search for unemployment-related series ids",
          "request": {
            "method": "GET",
            "path": "/series/search",
            "params": {
              "search_text": "unemployment rate",
              "file_type": "json"
            }
          }
        }
      ],
      "gotchas": [
        "Must pass file_type=json or you get XML",
        "api_key is required on every call",
        "Series IDs are case-sensitive uppercase codes"
      ]
    },
    "compliance": {
      "license": "other",
      "tosUrl": "https://fred.stlouisfed.org/docs/api/terms_of_use.html",
      "redistributionNotes": "Free API key required; underlying series may carry third-party copyright/licensing — check series-level notes before redistribution.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/fred.ts"
    }
  },
  {
    "id": "noaa-climate",
    "name": "NOAA Climate Data Online (CDO)",
    "agency": "NOAA National Centers for Environmental Information",
    "category": "climate",
    "status": "live",
    "api": {
      "baseUrl": "https://www.ncei.noaa.gov/cdo-web/api/v2",
      "protocol": "rest-json",
      "docsUrl": "https://www.ncdc.noaa.gov/cdo-web/webservices/v2",
      "endpoints": [
        {
          "id": "data",
          "path": "/data",
          "method": "GET",
          "description": "Historical climate observations by dataset, station, and date range"
        },
        {
          "id": "stations",
          "path": "/stations",
          "method": "GET",
          "description": "List/lookup weather stations"
        },
        {
          "id": "datasets",
          "path": "/datasets",
          "method": "GET",
          "description": "Available datasets (GHCND, GSOM, etc.)"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "header",
      "paramName": "token",
      "credentialRef": "env:NOAA_CDO_TOKEN",
      "signupUrl": "https://www.ncdc.noaa.gov/cdo-web/token"
    },
    "limits": {
      "dailyQuota": 10000,
      "perRequestMaxSeries": 1000,
      "rateLimitBehavior": "hard-reject",
      "notes": "5 requests/second and 10,000 requests/day per token. Distinct from the keyless real-time api.weather.gov (noaa-weather)."
    },
    "llmDocs": {
      "summary": "Historical/archival US climate records: daily and monthly temperature, precipitation, and station normals.",
      "queryGuide": "Pick a datasetid (e.g. GHCND for daily summaries), a stationid, and startdate/enddate, then call /data. Use /stations and /datasets for discovery.",
      "exampleQueries": [
        {
          "intent": "Daily summaries for one station, January 2026",
          "request": {
            "method": "GET",
            "path": "/data",
            "params": {
              "datasetid": "GHCND",
              "stationid": "GHCND:USW00023174",
              "startdate": "2026-01-01",
              "enddate": "2026-01-31"
            }
          }
        },
        {
          "intent": "List available datasets (GHCND, GSOM, ...)",
          "request": {
            "method": "GET",
            "path": "/datasets"
          }
        }
      ],
      "gotchas": [
        "Token goes in a 'token' HTTP header, not a query param",
        "Date range max 1 year per request for daily data",
        "Separate from real-time forecasts — this is the historical archive"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.ncdc.noaa.gov/cdo-web/termsofuse",
      "redistributionNotes": "US federal data, public domain. Attribution to NOAA NCEI requested.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/noaa-climate.ts"
    }
  },
  {
    "id": "noaa-weather",
    "name": "NWS / NOAA Weather API",
    "agency": "National Weather Service (NOAA)",
    "category": "weather",
    "status": "live",
    "api": {
      "baseUrl": "https://api.weather.gov",
      "protocol": "rest-json",
      "docsUrl": "https://www.weather.gov/documentation/services-web-api",
      "endpoints": [
        {
          "id": "points",
          "path": "/points/{lat},{lon}",
          "method": "GET",
          "description": "Resolve a lat/lon to grid, forecast office, and forecast URLs"
        },
        {
          "id": "forecast",
          "path": "/gridpoints/{office}/{gridX},{gridY}/forecast",
          "method": "GET",
          "description": "12-hour-period forecast for a grid cell"
        },
        {
          "id": "hourly",
          "path": "/gridpoints/{office}/{gridX},{gridY}/forecast/hourly",
          "method": "GET",
          "description": "Hourly forecast for a grid cell"
        },
        {
          "id": "alerts-active",
          "path": "/alerts/active",
          "method": "GET",
          "description": "Active watches/warnings/advisories, filterable by area/point/zone"
        },
        {
          "id": "stations-observations",
          "path": "/stations/{stationId}/observations/latest",
          "method": "GET",
          "description": "Latest observation from a station"
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No published hard quota. Requires a descriptive User-Agent header (contact email) or requests are rejected. Responses cached; respect Cache-Control/Expires."
    },
    "llmDocs": {
      "summary": "US weather forecasts, hourly forecasts, active alerts, and station observations. No API key; two-step flow (geocode point -> follow returned forecast URLs).",
      "queryGuide": "Always start with GET /points/{lat},{lon}; the response 'properties' contains gridId, gridX, gridY, and ready-made forecast/forecastHourly URLs. Do not construct gridpoint URLs by hand. US locations only.",
      "exampleQueries": [
        {
          "intent": "Forecast for Washington DC (step 1: resolve point)",
          "request": {
            "method": "GET",
            "path": "/points/38.8977,-77.0365"
          }
        },
        {
          "intent": "Active alerts for a state",
          "request": {
            "method": "GET",
            "path": "/alerts/active",
            "params": {
              "area": "CA"
            }
          }
        }
      ],
      "gotchas": [
        "User-Agent header is mandatory; include a contact email or you get 403 (the connector sets one automatically).",
        "Coordinates must be lat,lon (not lon,lat) and have limited decimal precision (API may 301-redirect to truncated coords).",
        "Only covers US territory; non-US points return 404.",
        "Two requests minimum per forecast (points then forecast)."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.weather.gov/disclaimer",
      "redistributionNotes": "US federal government work, public domain. Free to redistribute; do not imply NWS endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/noaa.ts"
    }
  },
  {
    "id": "nvd",
    "name": "NVD — National Vulnerability Database (CVE)",
    "agency": "NIST (National Institute of Standards and Technology)",
    "category": "cybersecurity",
    "status": "live",
    "api": {
      "baseUrl": "https://services.nvd.nist.gov/rest/json",
      "protocol": "rest-json",
      "docsUrl": "https://nvd.nist.gov/developers/vulnerabilities",
      "endpoints": [
        {
          "id": "cves",
          "path": "/cves/2.0",
          "method": "GET",
          "description": "Search CVE vulnerability records by id, keyword, CVSS severity, CPE, and date range."
        },
        {
          "id": "cve-history",
          "path": "/cvehistory/2.0",
          "method": "GET",
          "description": "Change history for CVE records."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "header",
      "paramName": "apiKey",
      "credentialRef": "env:NVD_API_KEY",
      "signupUrl": "https://nvd.nist.gov/developers/request-an-api-key"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "Works keyless at 5 requests per 30s rolling window; a free key raises it to 50 per 30s. resultsPerPage max 2000. Inject the key only when set (optional)."
    },
    "llmDocs": {
      "summary": "NIST National Vulnerability Database: CVE records with CVSS scores, affected products (CPE), references, and change history.",
      "queryGuide": "GET /cves/2.0 with cveId=CVE-YYYY-NNNN for one record, or filters: keywordSearch=, cvssV3Severity=(LOW|MEDIUM|HIGH|CRITICAL), cpeName=, pubStartDate/pubEndDate or lastModStartDate/lastModEndDate (ISO 8601, max 120-day span), resultsPerPage (max 2000), startIndex. The apiKey header is injected only when configured (works keyless at lower limits).",
      "exampleQueries": [
        {
          "intent": "Fetch one CVE by id",
          "request": {
            "method": "GET",
            "path": "/cves/2.0",
            "params": {
              "cveId": "CVE-2021-44228"
            }
          }
        },
        {
          "intent": "Critical CVEs matching a keyword",
          "request": {
            "method": "GET",
            "path": "/cves/2.0",
            "params": {
              "keywordSearch": "openssl",
              "cvssV3Severity": "CRITICAL",
              "resultsPerPage": "10"
            }
          }
        }
      ],
      "gotchas": [
        "Date-range filters max out at a 120-day span per request; window larger pulls.",
        "Pagination is startIndex/resultsPerPage (max 2000), with totalResults in the envelope.",
        "Keyless is 5 req/30s — bursts get HTTP 403/429; set NVD_API_KEY to raise to 50/30s (optional injection).",
        "cveId must be the full CVE-YYYY-NNNN form."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://nvd.nist.gov/developers/terms-of-use",
      "redistributionNotes": "US federal data, public domain. Terms request attribution and prohibit implying NIST endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/nvd.ts"
    }
  },
  {
    "id": "openfda",
    "name": "openFDA API",
    "agency": "U.S. Food and Drug Administration",
    "category": "health",
    "status": "live",
    "api": {
      "baseUrl": "https://api.fda.gov",
      "protocol": "rest-json",
      "docsUrl": "https://open.fda.gov/apis/",
      "endpoints": [
        {
          "id": "drug-event",
          "path": "/drug/event.json",
          "method": "GET",
          "description": "Adverse event reports (FAERS) for drugs."
        },
        {
          "id": "drug-enforcement",
          "path": "/drug/enforcement.json",
          "method": "GET",
          "description": "Drug recall enforcement reports."
        },
        {
          "id": "device-event",
          "path": "/device/event.json",
          "method": "GET",
          "description": "Medical device adverse event reports (MAUDE)."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:OPENFDA_API_KEY",
      "signupUrl": "https://open.fda.gov/apis/authentication/"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "Works keyless at lower limits (240 req/min, 1000/day per IP); a free api_key raises it (240 req/min, 120000/day). Inject the key only when set (mirror census-acs)."
    },
    "llmDocs": {
      "summary": "FDA data on drugs, devices, and foods: adverse events, recalls/enforcement, product labels, and the NDC directory.",
      "queryGuide": "Each domain has its own endpoint, e.g. /drug/event.json. Query with search=<field>:<value> (Lucene syntax, AND/OR, ranges, date ranges like [20240101+TO+20241231]), limit (max 1000), skip (max 25000), and count=<field> for aggregated counts instead of records. api_key is injected only when configured (works keyless otherwise).",
      "exampleQueries": [
        {
          "intent": "Count adverse-event reports by reaction for a drug",
          "request": {
            "method": "GET",
            "path": "/drug/event.json",
            "params": {
              "search": "patient.drug.medicinalproduct:aspirin",
              "count": "patient.reaction.reactionmeddrapt.exact"
            }
          }
        },
        {
          "intent": "Recent drug recall enforcement reports",
          "request": {
            "method": "GET",
            "path": "/drug/enforcement.json",
            "params": {
              "search": "report_date:[20240101+TO+20241231]",
              "limit": "5"
            }
          }
        }
      ],
      "gotchas": [
        "search uses Lucene field:value syntax; exact-match fields need the .exact suffix (especially for count=).",
        "count= returns aggregated buckets, not raw records — different response shape.",
        "Paging: limit max 1000, skip max 25000; beyond that, narrow the search.",
        "Keyless works but is rate-limited per IP; set OPENFDA_API_KEY to raise the daily cap (optional injection)."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://open.fda.gov/terms/",
      "redistributionNotes": "US federal data, public domain (CC0). openFDA is not for clinical decisions; terms prohibit implying FDA endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/openfda.ts"
    }
  },
  {
    "id": "regulations-gov",
    "name": "Regulations.gov API (v4)",
    "agency": "U.S. General Services Administration / eRulemaking",
    "category": "regulations",
    "status": "live",
    "api": {
      "baseUrl": "https://api.regulations.gov/v4",
      "protocol": "rest-json",
      "docsUrl": "https://open.gsa.gov/api/regulationsgov/",
      "endpoints": [
        {
          "id": "documents",
          "path": "/documents",
          "method": "GET",
          "description": "Search regulatory documents (rules, proposed rules, notices, supporting materials)."
        },
        {
          "id": "dockets",
          "path": "/dockets",
          "method": "GET",
          "description": "Search rulemaking dockets."
        },
        {
          "id": "comments",
          "path": "/comments",
          "method": "GET",
          "description": "Search public comments submitted on documents/dockets."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "header",
      "paramName": "X-Api-Key",
      "credentialRef": "env:REGULATIONS_API_KEY",
      "signupUrl": "https://open.gsa.gov/api/regulationsgov/#getting-started"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "api.data.gov key required in X-Api-Key. Hard limit 1000 requests/hour per key, then HTTP 429. page[size] max 250; results capped at 5000 per query (20 pages)."
    },
    "llmDocs": {
      "summary": "US federal rulemaking: regulatory documents, dockets, and public comments from Regulations.gov.",
      "queryGuide": "GET /documents, /dockets, or /comments with filter[*] params (e.g. filter[searchTerm], filter[agencyId], filter[postedDate][ge]), sort, page[size] (max 250), page[number]. The X-Api-Key header is injected by the gateway. Detail records are fetched by id at /documents/{id}, etc.",
      "exampleQueries": [
        {
          "intent": "Search documents by term for an agency",
          "request": {
            "method": "GET",
            "path": "/documents",
            "params": {
              "filter[searchTerm]": "emissions",
              "filter[agencyId]": "EPA",
              "page[size]": "5"
            }
          }
        },
        {
          "intent": "Comments posted after a date",
          "request": {
            "method": "GET",
            "path": "/comments",
            "params": {
              "filter[postedDate][ge]": "2024-01-01",
              "page[size]": "10"
            }
          }
        }
      ],
      "gotchas": [
        "Filters and paging are bracketed: filter[searchTerm], page[size], page[number].",
        "1000 req/hr hard cap per key, then 429.",
        "Results capped at 5000 per query (page[size] max 250 x 20 pages); use date/agency filters to narrow.",
        "Requires an api.data.gov key (REGULATIONS_API_KEY)."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.regulations.gov/user-notice",
      "redistributionNotes": "US federal data, public domain. api.data.gov ToS restricts key sharing — same concern as BLS; needs human review before going live.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/regulations-gov.ts"
    }
  },
  {
    "id": "sam-gov",
    "name": "SAM.gov — Entity & Exclusions API",
    "agency": "U.S. General Services Administration",
    "category": "procurement",
    "status": "planned",
    "api": {
      "baseUrl": "https://api.sam.gov",
      "protocol": "rest-json",
      "docsUrl": "https://open.gsa.gov/api/entity-api/",
      "endpoints": [
        {
          "id": "entity-management",
          "path": "/entity-information/v3/entities",
          "method": "GET",
          "description": "Search registered federal entities (by UEI, CAGE, name, registration status)."
        },
        {
          "id": "exclusions",
          "path": "/entity-information/v4/exclusions",
          "method": "GET",
          "description": "Search the exclusions list (parties barred from federal contracts/assistance)."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:SAM_API_KEY",
      "signupUrl": "https://sam.gov/profile/details"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "Personal/system api_key required, tied to a SAM.gov account with role-based daily caps (often ~10 req/day for unauthenticated-tier keys, more for federal/system accounts). Tight per-key quotas."
    },
    "llmDocs": {
      "summary": "Federal entity registrations (UEI/CAGE, business details) and the government-wide exclusions (debarment) list from SAM.gov.",
      "queryGuide": "GET /entity-information/v3/entities or /entity-information/v4/exclusions with query params such as ueiSAM, legalBusinessName, registrationStatus, samRegistered, and paging via page (0-based) and size. api_key is injected by the gateway. Field availability depends on the key's sensitivity role.",
      "exampleQueries": [
        {
          "intent": "Look up an entity by UEI",
          "request": {
            "method": "GET",
            "path": "/entity-information/v3/entities",
            "params": {
              "ueiSAM": "ABC123DEF456"
            }
          }
        },
        {
          "intent": "Search active registrations by business name",
          "request": {
            "method": "GET",
            "path": "/entity-information/v3/entities",
            "params": {
              "legalBusinessName": "Acme",
              "registrationStatus": "A",
              "size": "10"
            }
          }
        }
      ],
      "gotchas": [
        "api_key is tied to a SAM.gov account; quotas and which fields return depend on the account's role (public vs FOUO/sensitive).",
        "Daily caps are low for public keys (~10/day); bring your own key (SAM_API_KEY).",
        "Paging is page (0-based) and size.",
        "Endpoint versions differ per resource (entities v3, exclusions v4) — confirm against the docs before implementing."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://open.gsa.gov/api/entity-api/",
      "redistributionNotes": "US federal data, public domain, but sensitive (FOUO) fields are access-controlled by key role and must not be redistributed. Needs human review before going live.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/sam-gov.ts"
    }
  },
  {
    "id": "sec-edgar",
    "name": "SEC EDGAR — company filings & XBRL facts",
    "agency": "U.S. Securities and Exchange Commission",
    "category": "finance",
    "status": "live",
    "api": {
      "baseUrl": "https://data.sec.gov",
      "protocol": "rest-json",
      "docsUrl": "https://www.sec.gov/edgar/sec-api-documentation",
      "endpoints": [
        {
          "id": "submissions",
          "path": "/submissions/CIK{cik}.json",
          "method": "GET",
          "description": "All filings for a company by zero-padded 10-digit CIK"
        },
        {
          "id": "company-concept",
          "path": "/api/xbrl/companyconcept/CIK{cik}/{taxonomy}/{tag}.json",
          "method": "GET",
          "description": "One tagged XBRL financial fact across all filings"
        },
        {
          "id": "company-facts",
          "path": "/api/xbrl/companyfacts/CIK{cik}.json",
          "method": "GET",
          "description": "All XBRL facts for a company"
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "hard-reject",
      "notes": "No key, but a descriptive User-Agent (AppName contact@email) is mandatory. Max ~10 requests/sec per IP."
    },
    "llmDocs": {
      "summary": "US public-company filings, financial statements, and XBRL-tagged facts from SEC EDGAR.",
      "queryGuide": "CIK must be zero-padded to 10 digits. Start from /submissions/CIK{cik}.json to list filings, or pull a single metric via companyconcept (taxonomy us-gaap, tag e.g. Revenues).",
      "exampleQueries": [
        {
          "intent": "All filings for Apple (CIK 320193)",
          "request": {
            "method": "GET",
            "path": "/submissions/CIK0000320193.json"
          }
        },
        {
          "intent": "Apple revenue across filings (us-gaap Revenues)",
          "request": {
            "method": "GET",
            "path": "/api/xbrl/companyconcept/CIK0000320193/us-gaap/Revenues.json"
          }
        }
      ],
      "gotchas": [
        "CIK must be zero-padded to 10 digits",
        "User-Agent header is mandatory",
        "Free and keyless — send a descriptive User-Agent header (SEC requires one)."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.sec.gov/os/webmaster-faq#developers",
      "redistributionNotes": "US federal data, public domain.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/sec-edgar.ts"
    }
  },
  {
    "id": "treasury-fiscal",
    "name": "Treasury Fiscal Data — debt, spending & rates",
    "agency": "U.S. Department of the Treasury (Bureau of the Fiscal Service)",
    "category": "finance",
    "status": "live",
    "api": {
      "baseUrl": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service",
      "protocol": "rest-json",
      "docsUrl": "https://fiscaldata.treasury.gov/api-documentation/",
      "endpoints": [
        {
          "id": "debt-to-penny",
          "path": "/v2/accounting/od/debt_to_penny",
          "method": "GET",
          "description": "Total public debt outstanding, daily."
        },
        {
          "id": "exchange-rates",
          "path": "/v1/accounting/od/rates_of_exchange",
          "method": "GET",
          "description": "Treasury reporting rates of exchange by country/currency and quarter."
        },
        {
          "id": "avg-interest-rates",
          "path": "/v2/accounting/od/avg_interest_rates",
          "method": "GET",
          "description": "Average interest rates on US Treasury securities, monthly."
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key. Default page[size] is 100; max page[size] is 10000. No published hard quota."
    },
    "llmDocs": {
      "summary": "Federal financial data: national debt, daily Treasury statement, average interest rates, exchange rates, and spending/revenue, by dataset.",
      "queryGuide": "Each dataset is its own versioned path under the base. Shape the response with: fields (comma-separated columns), filter (e.g. record_date:gte:2024-01-01), sort (prefix '-' for descending, e.g. -record_date), page[size] and page[number], format=json (default). Field/column names are dataset-specific — see the dataset's docs page.",
      "exampleQueries": [
        {
          "intent": "Latest national debt to the penny",
          "request": {
            "method": "GET",
            "path": "/v2/accounting/od/debt_to_penny",
            "params": {
              "sort": "-record_date",
              "page[size]": "1"
            }
          }
        },
        {
          "intent": "2024 month-end exchange rates for the Euro",
          "request": {
            "method": "GET",
            "path": "/v1/accounting/od/rates_of_exchange",
            "params": {
              "filter": "record_date:gte:2024-01-01,currency:eq:Euro",
              "fields": "country_currency_desc,exchange_rate,record_date",
              "sort": "-record_date"
            }
          }
        }
      ],
      "gotchas": [
        "Paging uses bracketed params: page[size] and page[number], not limit/offset.",
        "filter syntax is field:operator:value (operators lt, lte, gt, gte, eq, in) joined by commas.",
        "sort defaults to ascending; prefix the field with '-' for descending (e.g. -record_date).",
        "Column names differ per dataset — request fields= using that dataset's documented column names."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://fiscaldata.treasury.gov/api-documentation/",
      "redistributionNotes": "US federal data, public domain. Free to redistribute; attribution requested.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/treasury-fiscal.ts"
    }
  },
  {
    "id": "usaspending",
    "name": "USAspending — federal spending API",
    "agency": "U.S. Department of the Treasury",
    "category": "spending",
    "status": "live",
    "api": {
      "baseUrl": "https://api.usaspending.gov/api/v2",
      "protocol": "rest-json",
      "docsUrl": "https://api.usaspending.gov/docs/endpoints",
      "endpoints": [
        {
          "id": "spending-by-award",
          "path": "/search/spending_by_award/",
          "method": "POST",
          "description": "Search awards (contracts, grants) by filters"
        },
        {
          "id": "agency-overview",
          "path": "/agency/{toptier_code}/",
          "method": "GET",
          "description": "Budgetary overview for a federal agency"
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key required. No published hard quota; be courteous with pagination (POST filters with page/limit)."
    },
    "llmDocs": {
      "summary": "US federal government spending: contracts, grants, loans, and agency budgets, searchable by recipient, agency, location, and time.",
      "queryGuide": "Most search endpoints are POST with a JSON 'filters' object. Build filters (time_period, agencies, award_type_codes) and POST to /search/spending_by_award/.",
      "exampleQueries": [
        {
          "intent": "Contract awards for FY2024 (top 5 by amount)",
          "request": {
            "method": "POST",
            "path": "/search/spending_by_award/",
            "body": {
              "filters": {
                "award_type_codes": [
                  "A",
                  "B",
                  "C",
                  "D"
                ],
                "time_period": [
                  {
                    "start_date": "2023-10-01",
                    "end_date": "2024-09-30"
                  }
                ]
              },
              "fields": [
                "Award ID",
                "Recipient Name",
                "Award Amount"
              ],
              "limit": 5
            }
          }
        },
        {
          "intent": "List agency toptier codes (to resolve an agency name to a code)",
          "request": {
            "method": "GET",
            "path": "/references/toptier_agencies/"
          }
        }
      ],
      "gotchas": [
        "Keyless but most useful endpoints are POST, not GET",
        "Filters object schema is strict — malformed filters return 422",
        "Large result sets require pagination via page/limit"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.usaspending.gov/about",
      "redistributionNotes": "US federal data, public domain (DATA Act). Free to redistribute.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/usaspending.ts"
    }
  },
  {
    "id": "usgs-earthquake",
    "name": "USGS Earthquake Catalog (FDSN event)",
    "agency": "U.S. Geological Survey",
    "category": "geology",
    "status": "live",
    "api": {
      "baseUrl": "https://earthquake.usgs.gov/fdsnws/event/1",
      "protocol": "rest-json",
      "docsUrl": "https://earthquake.usgs.gov/fdsnws/event/1/",
      "endpoints": [
        {
          "id": "query",
          "path": "/query",
          "method": "GET",
          "description": "Search the earthquake catalog by time, magnitude, location, and depth; returns GeoJSON when format=geojson."
        },
        {
          "id": "count",
          "path": "/count",
          "method": "GET",
          "description": "Count matching events without returning them (same filter params as /query)."
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "No API key. A single query returns at most 20000 events; larger queries are rejected with HTTP 400 — narrow the time window or raise minmagnitude. Use /count to size a query first."
    },
    "llmDocs": {
      "summary": "Global real-time and historical earthquake catalog: magnitude, location, depth, and time for seismic events.",
      "queryGuide": "GET /query?format=geojson with filters: starttime/endtime (ISO 8601 or YYYY-MM-DD), minmagnitude/maxmagnitude, latitude+longitude+maxradiuskm (radial), or minlatitude/maxlatitude/minlongitude/maxlongitude (box), mindepth/maxdepth, orderby (time, time-asc, magnitude, magnitude-asc), limit. Always set format=geojson for clean JSON; the default format is QuakeML XML. Use /count with the same params to size a result first.",
      "exampleQueries": [
        {
          "intent": "Magnitude 5+ quakes worldwide in a one-day window",
          "request": {
            "method": "GET",
            "path": "/query",
            "params": {
              "format": "geojson",
              "starttime": "2024-01-01",
              "endtime": "2024-01-02",
              "minmagnitude": "5"
            }
          }
        },
        {
          "intent": "Recent quakes within 200km of Los Angeles, strongest first",
          "request": {
            "method": "GET",
            "path": "/query",
            "params": {
              "format": "geojson",
              "latitude": "34.05",
              "longitude": "-118.25",
              "maxradiuskm": "200",
              "minmagnitude": "3",
              "orderby": "magnitude",
              "limit": "20"
            }
          }
        }
      ],
      "gotchas": [
        "Set format=geojson — the default response format is QuakeML (XML), not JSON.",
        "A query returning more than 20000 events fails with HTTP 400: narrow starttime/endtime or raise minmagnitude.",
        "Times are UTC; bare dates (YYYY-MM-DD) imply 00:00:00 UTC.",
        "Radial search needs latitude, longitude, AND maxradiuskm together."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
      "redistributionNotes": "US federal data, public domain. Attribution to USGS requested.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/usgs-earthquake.ts"
    }
  },
  {
    "id": "usgs-water",
    "name": "USGS Water Data (NWIS → OGC migration)",
    "agency": "U.S. Geological Survey",
    "category": "water",
    "status": "planned",
    "api": {
      "baseUrl": "https://api.waterdata.usgs.gov",
      "protocol": "rest-json",
      "docsUrl": "https://api.waterdata.usgs.gov/docs/",
      "endpoints": [
        {
          "id": "ogc-collections",
          "path": "/ogcapi/v0/collections",
          "method": "GET",
          "description": "PROVISIONAL — OGC API collections (new keyed Water Data API). Confirm exact paths before implementing; see notes.md."
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:USGS_WATER_API_KEY",
      "signupUrl": "https://api.waterdata.usgs.gov/signup/"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "error",
      "notes": "MIGRATION IN PROGRESS. Legacy NWIS (waterservices.usgs.gov) is keyless but being retired; the new api.waterdata.usgs.gov OGC API requires a key with per-key quotas. Endpoints below are provisional — vet before implementing."
    },
    "llmDocs": {
      "summary": "US streamflow, gage height, and water-quality observations from USGS monitoring sites (NWIS, migrating to the new OGC-based Water Data API).",
      "queryGuide": "DO NOT rely on these endpoints yet — USGS is mid-migration from legacy NWIS (waterservices.usgs.gov/nwis/iv, keyless) to the new keyed OGC API at api.waterdata.usgs.gov. Confirm the target host, version, and collection paths against the live docs during the Vet phase before wiring a connector.",
      "exampleQueries": [
        {
          "intent": "PROVISIONAL — list OGC collections once the migration target is confirmed",
          "request": {
            "method": "GET",
            "path": "/ogcapi/v0/collections"
          }
        }
      ],
      "gotchas": [
        "Endpoints are PROVISIONAL — USGS is migrating NWIS to a new keyed OGC API; legacy waterservices.usgs.gov may differ or be retired.",
        "Do not guess paths: vet the live docs and confirm which host (legacy vs api.waterdata.usgs.gov) to target before implementing.",
        "Requires a bring-your-own API key (USGS_WATER_API_KEY); connector not yet shipped."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
      "redistributionNotes": "US federal data, public domain. Attribution to USGS requested. Endpoint/auth model unsettled during migration — review before going live.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/usgs-water.ts"
    }
  }
] as const;
