// AUTO-GENERATED by scripts/build-catalog.ts — DO NOT EDIT.
// Source of truth: sources/<id>/source.json. Regenerate with: npm run catalog

import type { SourceSpec } from "./schema.js";

export const SOURCES: readonly SourceSpec[] = [
  {
    "id": "bls-public-data",
    "name": "BLS Public Data API",
    "agency": "Bureau of Labor Statistics",
    "category": "economy",
    "tier": "free",
    "status": "planned",
    "api": {
      "baseUrl": "https://api.bls.gov/publicAPI/v2",
      "protocol": "rest-json",
      "docsUrl": "https://www.bls.gov/developers/",
      "endpoints": [
        {
          "id": "timeseries",
          "path": "/timeseries/data/",
          "method": "POST",
          "description": "Fetch one or more series by ID over a year range"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "body",
      "paramName": "registrationkey",
      "credentialRef": "env:BLS_API_KEY",
      "signupUrl": "https://data.bls.gov/registrationEngine/"
    },
    "limits": {
      "dailyQuota": 500,
      "perRequestMaxSeries": 50,
      "rateLimitBehavior": "hard-reject",
      "notes": "Quota is per key — multiplexing risk, monitor usage"
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "US labor statistics: unemployment, CPI, wages, employment by industry and region.",
      "queryGuide": "Series IDs are structured codes, e.g. LAUCN040010000000005 = Local Area Unemployment, county-level. Prefix determines survey: LA=local unemployment, CU=CPI urban, CE=employment.",
      "exampleQueries": [
        {
          "intent": "National unemployment rate, last 2 years",
          "request": {
            "seriesid": [
              "LNS14000000"
            ],
            "startyear": "2024",
            "endyear": "2026"
          }
        }
      ],
      "gotchas": [
        "POST not GET for multi-series",
        "Years are strings, not ints",
        "No discovery endpoint — series IDs must be constructed or known"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.bls.gov/developers/termsOfService.htm",
      "redistributionNotes": "ToS prohibits sharing registration keys; centralized key use needs review",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/bls.ts"
    }
  },
  {
    "id": "census-acs",
    "name": "US Census Bureau — American Community Survey",
    "agency": "U.S. Census Bureau",
    "category": "demographics",
    "tier": "free",
    "status": "planned",
    "api": {
      "baseUrl": "https://api.census.gov/data",
      "protocol": "rest-json",
      "docsUrl": "https://www.census.gov/data/developers/data-sets/acs-5year.html",
      "endpoints": [
        {
          "id": "acs5",
          "path": "/{year}/acs/acs5",
          "method": "GET",
          "description": "ACS 5-year detailed tables: select variables with get=, geography with for=/in="
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "key",
      "credentialRef": "env:CENSUS_API_KEY",
      "signupUrl": "https://api.census.gov/data/key_signup.html"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "Calls without a key are limited to ~500/day per IP; a free key raises the cap. Max 50 variables per get= request."
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "US population, income, housing, education and demographic estimates by geography (nation, state, county, tract, block group).",
      "queryGuide": "Returns a JSON array-of-arrays; row 0 is the header. Select variables via get= (e.g. NAME,B01001_001E) and geography via for=/in=. e.g. B01001_001E = total population.",
      "exampleQueries": [
        {
          "intent": "Total population by state, 2022 ACS5",
          "request": {
            "method": "GET",
            "path": "/2022/acs/acs5",
            "params": {
              "get": "NAME,B01001_001E",
              "for": "state:*"
            }
          }
        },
        {
          "intent": "Median household income for one county",
          "request": {
            "method": "GET",
            "path": "/2022/acs/acs5",
            "params": {
              "get": "NAME,B19013_001E",
              "for": "county:031",
              "in": "state:08"
            }
          }
        }
      ],
      "gotchas": [
        "Response is array-of-arrays, not array-of-objects",
        "Variable codes end in E for estimate, M for margin of error",
        "Geography hierarchy matters: 'in=' is required for sub-state geos"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.census.gov/data/developers/about/terms-of-service.html",
      "redistributionNotes": "US federal data, public domain. ToS requires attribution and prohibits implying Census endorsement.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/census-acs.ts"
    }
  },
  {
    "id": "epa-airnow",
    "name": "EPA AirNow API",
    "agency": "Environmental Protection Agency",
    "category": "environment",
    "tier": "free",
    "status": "planned",
    "api": {
      "baseUrl": "https://www.airnowapi.org",
      "protocol": "rest-json",
      "docsUrl": "https://docs.airnowapi.org/",
      "endpoints": [
        {
          "id": "observation-by-zip",
          "path": "/aq/observation/zipCode/current/",
          "method": "GET",
          "description": "Current AQI observations by ZIP code"
        },
        {
          "id": "observation-by-latlon",
          "path": "/aq/observation/latLong/current/",
          "method": "GET",
          "description": "Current AQI observations by lat/lon"
        },
        {
          "id": "forecast-by-zip",
          "path": "/aq/forecast/zipCode/",
          "method": "GET",
          "description": "AQI forecast by ZIP code"
        },
        {
          "id": "data",
          "path": "/aq/data/",
          "method": "GET",
          "description": "Raw monitoring data by bounding box and parameter over a time range"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "API_KEY",
      "credentialRef": "env:AIRNOW_API_KEY",
      "signupUrl": "https://docs.airnowapi.org/account/request/"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "hard-reject",
      "notes": "Default rate limit ~500 requests/hour per key (confirm in account dashboard). Verify exact hourly cap before relying on it."
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "Real-time and forecast US air quality (AQI) for ozone, PM2.5, PM10 by ZIP, lat/lon, or bounding box.",
      "queryGuide": "Use zipCode or latLong observation endpoints for point lookups; use /aq/data/ with a bounding box (BBOX) for area scans. Request format=application/json explicitly.",
      "exampleQueries": [
        {
          "intent": "Current AQI for a ZIP",
          "request": {
            "method": "GET",
            "url": "https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=90210&distance=25&API_KEY={key}"
          }
        },
        {
          "intent": "AQI forecast by lat/lon",
          "request": {
            "method": "GET",
            "url": "https://www.airnowapi.org/aq/forecast/latLong/?format=application/json&latitude=34.09&longitude=-118.41&date=2026-06-11&API_KEY={key}"
          }
        }
      ],
      "gotchas": [
        "format parameter is literally 'application/json' as a query value, not an Accept header.",
        "Coverage gaps where no nearby monitor exists; empty array means no station in range, not an error.",
        "Hourly rate limit is enforced and resets hourly; batch/cache aggressively."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://docs.airnowapi.org/faq",
      "redistributionNotes": "US federal data, public domain. AirNow ToS requires attribution to AirNow and prohibits implying EPA endorsement.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/epa-airnow.ts"
    }
  },
  {
    "id": "fred",
    "name": "FRED — Federal Reserve Economic Data",
    "agency": "Federal Reserve Bank of St. Louis",
    "category": "economy",
    "tier": "free",
    "status": "planned",
    "api": {
      "baseUrl": "https://api.stlouisfed.org/fred",
      "protocol": "rest-json",
      "docsUrl": "https://fred.stlouisfed.org/docs/api/fred/",
      "endpoints": [
        {
          "id": "series-observations",
          "path": "/series/observations",
          "method": "GET",
          "description": "Observation values for an economic data series by series_id"
        },
        {
          "id": "series-search",
          "path": "/series/search",
          "method": "GET",
          "description": "Search series by text"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "query",
      "paramName": "api_key",
      "credentialRef": "env:FRED_API_KEY",
      "signupUrl": "https://fredaccount.stlouisfed.org/apikeys"
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "hard-reject",
      "notes": "120 requests/minute per key. Default response is XML — request file_type=json explicitly."
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "US and international macroeconomic time series: GDP, inflation, interest rates, employment, money supply.",
      "queryGuide": "Identify a series_id (e.g. GDP, CPIAUCSL, UNRATE) then call /series/observations?series_id=...&file_type=json. Use /series/search to discover series_ids.",
      "exampleQueries": [
        {
          "intent": "Monthly CPI (all urban) observations",
          "request": {
            "method": "GET",
            "path": "/series/observations",
            "params": {
              "series_id": "CPIAUCSL",
              "file_type": "json"
            }
          }
        }
      ],
      "gotchas": [
        "Must pass file_type=json or you get XML",
        "api_key is required on every call",
        "Series IDs are case-sensitive uppercase codes"
      ]
    },
    "compliance": {
      "license": "other",
      "tosUrl": "https://fred.stlouisfed.org/docs/api/terms_of_use.html",
      "redistributionNotes": "Free API key required; underlying series may carry third-party copyright/licensing — check series-level notes before redistribution.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/fred.ts"
    }
  },
  {
    "id": "noaa-climate",
    "name": "NOAA Climate Data Online (CDO)",
    "agency": "NOAA National Centers for Environmental Information",
    "category": "climate",
    "tier": "free",
    "status": "planned",
    "api": {
      "baseUrl": "https://www.ncei.noaa.gov/cdo-web/api/v2",
      "protocol": "rest-json",
      "docsUrl": "https://www.ncdc.noaa.gov/cdo-web/webservices/v2",
      "endpoints": [
        {
          "id": "data",
          "path": "/data",
          "method": "GET",
          "description": "Historical climate observations by dataset, station, and date range"
        },
        {
          "id": "stations",
          "path": "/stations",
          "method": "GET",
          "description": "List/lookup weather stations"
        },
        {
          "id": "datasets",
          "path": "/datasets",
          "method": "GET",
          "description": "Available datasets (GHCND, GSOM, etc.)"
        }
      ]
    },
    "auth": {
      "type": "api-key",
      "placement": "header",
      "paramName": "token",
      "credentialRef": "env:NOAA_CDO_TOKEN",
      "signupUrl": "https://www.ncdc.noaa.gov/cdo-web/token"
    },
    "limits": {
      "dailyQuota": 10000,
      "perRequestMaxSeries": 1000,
      "rateLimitBehavior": "hard-reject",
      "notes": "5 requests/second and 10,000 requests/day per token. Distinct from the keyless real-time api.weather.gov (noaa-weather)."
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "Historical/archival US climate records: daily and monthly temperature, precipitation, and station normals.",
      "queryGuide": "Pick a datasetid (e.g. GHCND for daily summaries), a stationid, and startdate/enddate, then call /data. Use /stations and /datasets for discovery.",
      "exampleQueries": [
        {
          "intent": "Daily summaries for a station over a month",
          "request": {
            "method": "GET",
            "path": "/data",
            "params": {
              "datasetid": "GHCND",
              "stationid": "GHCND:USW00023174",
              "startdate": "2026-01-01",
              "enddate": "2026-01-31"
            }
          }
        }
      ],
      "gotchas": [
        "Token goes in a 'token' HTTP header, not a query param",
        "Date range max 1 year per request for daily data",
        "Separate from real-time forecasts — this is the historical archive"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.ncdc.noaa.gov/cdo-web/termsofuse",
      "redistributionNotes": "US federal data, public domain. Attribution to NOAA NCEI requested.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/noaa-climate.ts"
    }
  },
  {
    "id": "noaa-weather",
    "name": "NWS / NOAA Weather API",
    "agency": "National Weather Service (NOAA)",
    "category": "weather",
    "tier": "free",
    "status": "live",
    "api": {
      "baseUrl": "https://api.weather.gov",
      "protocol": "rest-json",
      "docsUrl": "https://www.weather.gov/documentation/services-web-api",
      "endpoints": [
        {
          "id": "points",
          "path": "/points/{lat},{lon}",
          "method": "GET",
          "description": "Resolve a lat/lon to grid, forecast office, and forecast URLs"
        },
        {
          "id": "forecast",
          "path": "/gridpoints/{office}/{gridX},{gridY}/forecast",
          "method": "GET",
          "description": "12-hour-period forecast for a grid cell"
        },
        {
          "id": "hourly",
          "path": "/gridpoints/{office}/{gridX},{gridY}/forecast/hourly",
          "method": "GET",
          "description": "Hourly forecast for a grid cell"
        },
        {
          "id": "alerts-active",
          "path": "/alerts/active",
          "method": "GET",
          "description": "Active watches/warnings/advisories, filterable by area/point/zone"
        },
        {
          "id": "stations-observations",
          "path": "/stations/{stationId}/observations/latest",
          "method": "GET",
          "description": "Latest observation from a station"
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No published hard quota. Requires a descriptive User-Agent header (contact email) or requests are rejected. Responses cached; respect Cache-Control/Expires."
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "US weather forecasts, hourly forecasts, active alerts, and station observations. No API key; two-step flow (geocode point -> follow returned forecast URLs).",
      "queryGuide": "Always start with GET /points/{lat},{lon}; the response 'properties' contains gridId, gridX, gridY, and ready-made forecast/forecastHourly URLs. Do not construct gridpoint URLs by hand. US locations only.",
      "exampleQueries": [
        {
          "intent": "Forecast for Washington DC (step 1: resolve point)",
          "request": {
            "method": "GET",
            "path": "/points/38.8977,-77.0365"
          }
        },
        {
          "intent": "Active alerts for a state",
          "request": {
            "method": "GET",
            "path": "/alerts/active",
            "params": {
              "area": "CA"
            }
          }
        }
      ],
      "gotchas": [
        "User-Agent header is mandatory; include a contact email or you get 403 (the connector sets one automatically).",
        "Coordinates must be lat,lon (not lon,lat) and have limited decimal precision (API may 301-redirect to truncated coords).",
        "Only covers US territory; non-US points return 404.",
        "Two requests minimum per forecast (points then forecast)."
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.weather.gov/disclaimer",
      "redistributionNotes": "US federal government work, public domain. Free to redistribute; do not imply NWS endorsement.",
      "reviewedDate": "2026-06-11"
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": "2026-06-11",
      "connectorPath": "src/connectors/noaa.ts"
    }
  },
  {
    "id": "sec-edgar",
    "name": "SEC EDGAR — company filings & XBRL facts",
    "agency": "U.S. Securities and Exchange Commission",
    "category": "finance",
    "tier": "premium",
    "status": "planned",
    "api": {
      "baseUrl": "https://data.sec.gov",
      "protocol": "rest-json",
      "docsUrl": "https://www.sec.gov/edgar/sec-api-documentation",
      "endpoints": [
        {
          "id": "submissions",
          "path": "/submissions/CIK{cik}.json",
          "method": "GET",
          "description": "All filings for a company by zero-padded 10-digit CIK"
        },
        {
          "id": "company-concept",
          "path": "/api/xbrl/companyconcept/CIK{cik}/{taxonomy}/{tag}.json",
          "method": "GET",
          "description": "One tagged XBRL financial fact across all filings"
        },
        {
          "id": "company-facts",
          "path": "/api/xbrl/companyfacts/CIK{cik}.json",
          "method": "GET",
          "description": "All XBRL facts for a company"
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "hard-reject",
      "notes": "No key, but a descriptive User-Agent (AppName contact@email) is mandatory. Max ~10 requests/sec per IP."
    },
    "pricing": {
      "model": "metered",
      "feePerCallCents": 2
    },
    "llmDocs": {
      "summary": "US public-company filings, financial statements, and XBRL-tagged facts from SEC EDGAR.",
      "queryGuide": "CIK must be zero-padded to 10 digits. Start from /submissions/CIK{cik}.json to list filings, or pull a single metric via companyconcept (taxonomy us-gaap, tag e.g. Revenues).",
      "exampleQueries": [
        {
          "intent": "All filings for Apple (CIK 320193)",
          "request": {
            "method": "GET",
            "path": "/submissions/CIK0000320193.json"
          }
        }
      ],
      "gotchas": [
        "CIK must be zero-padded to 10 digits",
        "User-Agent header is mandatory",
        "Premium tier — metered behind HTTP 402 until billing is enabled"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.sec.gov/os/webmaster-faq#developers",
      "redistributionNotes": "US federal data, public domain. Premium tier reflects gateway metering, not upstream cost.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/sec-edgar.ts"
    }
  },
  {
    "id": "usaspending",
    "name": "USAspending — federal spending API",
    "agency": "U.S. Department of the Treasury",
    "category": "spending",
    "tier": "free",
    "status": "planned",
    "api": {
      "baseUrl": "https://api.usaspending.gov/api/v2",
      "protocol": "rest-json",
      "docsUrl": "https://api.usaspending.gov/docs/endpoints",
      "endpoints": [
        {
          "id": "spending-by-award",
          "path": "/search/spending_by_award/",
          "method": "POST",
          "description": "Search awards (contracts, grants) by filters"
        },
        {
          "id": "agency-overview",
          "path": "/agency/{toptier_code}/",
          "method": "GET",
          "description": "Budgetary overview for a federal agency"
        }
      ]
    },
    "auth": {
      "type": "none",
      "placement": null,
      "paramName": null,
      "credentialRef": null,
      "signupUrl": null
    },
    "limits": {
      "dailyQuota": null,
      "perRequestMaxSeries": null,
      "rateLimitBehavior": "throttle",
      "notes": "No API key required. No published hard quota; be courteous with pagination (POST filters with page/limit)."
    },
    "pricing": {
      "model": "free",
      "feePerCallCents": null
    },
    "llmDocs": {
      "summary": "US federal government spending: contracts, grants, loans, and agency budgets, searchable by recipient, agency, location, and time.",
      "queryGuide": "Most search endpoints are POST with a JSON 'filters' object. Build filters (time_period, agencies, award_type_codes) and POST to /search/spending_by_award/.",
      "exampleQueries": [
        {
          "intent": "Contract awards in FY2025 for one agency",
          "request": {
            "method": "POST",
            "path": "/search/spending_by_award/",
            "body": {
              "filters": {
                "time_period": [
                  {
                    "start_date": "2024-10-01",
                    "end_date": "2025-09-30"
                  }
                ],
                "award_type_codes": [
                  "A",
                  "B",
                  "C",
                  "D"
                ]
              },
              "fields": [
                "Award ID",
                "Recipient Name",
                "Award Amount"
              ],
              "limit": 10
            }
          }
        }
      ],
      "gotchas": [
        "Keyless but most useful endpoints are POST, not GET",
        "Filters object schema is strict — malformed filters return 422",
        "Large result sets require pagination via page/limit"
      ]
    },
    "compliance": {
      "license": "public-domain",
      "tosUrl": "https://www.usaspending.gov/about",
      "redistributionNotes": "US federal data, public domain (DATA Act). Free to redistribute.",
      "reviewedDate": null
    },
    "meta": {
      "addedDate": "2026-06-11",
      "lastTestedDate": null,
      "connectorPath": "src/connectors/usaspending.ts"
    }
  }
] as const;
