/**
 * Codegen the runtime catalog from sources/<id>/source.json.
 *
 * Why generate instead of reading at runtime: Vercel serverless functions are
 * bundled by esbuild and do not reliably ship loose repo files (sources/ is not
 * traced from a static import). Compiling the validated specs into a committed
 * TS module guarantees the catalog is in the function bundle. Re-run after any
 * source.json change; the output is committed.
 *
 *   npx tsx scripts/build-catalog.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadSources, REPO_ROOT } from "../src/catalog/loader.js";

const { specs, errors } = loadSources();

if (errors.length > 0) {
  console.error(`✗ Refusing to generate catalog — ${errors.length} invalid source(s):`);
  for (const e of errors) console.error(`  ${e.sourceDir}: ${e.error}`);
  process.exit(1);
}

const out = join(REPO_ROOT, "src", "catalog", "catalog.generated.ts");
const banner = `// AUTO-GENERATED by scripts/build-catalog.ts — DO NOT EDIT.
// Source of truth: sources/<id>/source.json. Regenerate with: npm run catalog
`;

const body = `import type { SourceSpec } from "./schema.js";

export const SOURCES: readonly SourceSpec[] = ${JSON.stringify(specs, null, 2)} as const;
`;

writeFileSync(out, banner + "\n" + body);
console.log(`✓ Wrote ${specs.length} sources → src/catalog/catalog.generated.ts`);
